### PR TITLE
Fix ignore

### PR DESCRIPTION
**Pull request by lukeapage**
Continuation of #1967

commits need squashing, left in to see what I did

### CODE REVIEW

**Comment by jugglinmike** [comment]
This is really nice. What do you think about this simplification? https://github.com/jugglinmike/jshint/commit/bbcdf38bdcb496e60caeebeef28a99b5cea6b1e3

**Comment by lukeapage** [comment]
yes please go ahead and squash that in when you merge

**Comment by lukeapage** [comment]
just tested and all of the examples in #1465 are fixed by this PR

**Comment by lukeapage** [comment]
and #2215 is also fixed by this

**Comment by lukeapage** [comment]
and #1792 is also fixed by this

**Comment by jugglinmike** [comment]
> yes please go ahead and squash that in when you merge

In this case, we have multiple authors collaborating on a single feature. Each author's changeset incrementally defines the fix, so it would be inappropriate to simply cherry pick the commits. At the same time, squashing hides the history in a way that is disingenuous. The individual commits may not be useful on their own, but it's not quite correct to say that you or Cait or I were the sole author. So although we generally, discourage merge commits for landing patches, I think this is a perfect circumstance!

Merged to `master` at commit 39709b1e4c611973394ae7c3f3e1f6f989d15301

**Pull request closed without merging**
