### PR TITLE
[[FIX]] allow trailing comma in ArrayBindingPattern

### PR DESCRIPTION
**Pull request by caitp**
Also, disallow commas after rest elements in ArrayBindingPattern.

### CODE REVIEW

**Comment by rwaldron** [comment]
I read right past this earlier today:

**Comment by caitp** [comment]
yup, me too... that last `opt` was invisible :(

**Comment by rwaldron** [comment]
As ridiculous as 4 releases in two days is, I think this is important to have in the wild.

**Comment by caitp** [comment]
I'm going to try to fix the other issue in #2223 first, if you want to wait a few hours

**Comment by caitp** [comment]
fixup removes handling of "..." in advance(), since it's handled specially everywhere that it's valid.

**Pull request closed without merging**
