### PR TITLE
Using an option object to pass doFunction params

### PR DESCRIPTION
**Pull request by sebv**
Avoids passing null or undefined parameters everywhere.

### CODE REVIEW

**Comment by Globegitter** [comment]
Any reason this is not being merged? Would love to see support for this and more importantly https://github.com/jshint/jshint/pull/2077

**Comment by jugglinmike** [comment]
@Globegitter As discussed in #2077, that feature is not under consideration for inclusion in JSHint at this time; it was shared as an exploration into a future plugin system.

**Comment by nicolo-ribaudo** [comment]
I think this PR can be closed, as now [`doFunction` requires an object as parameter](https://github.com/jshint/jshint/blob/master/src/jshint.js#L2907-L2925).

**Comment by lukeapage** [comment]
good spotting..

**Pull request closed without merging**
