### PR TITLE
[[FIX]] Correct interpretation of whitespace

### PR DESCRIPTION
**Pull request by jugglinmike**
@rwaldron I've been working on the `v2.10.0` branch, and it took me quite some time to figure out what was going wrong here (I only recently upgraded my development machine to Node.js version 8.)

### CODE REVIEW

**Comment by rwaldron** [comment]
LGTM

However, Travis is failing for the same reason: https://github.com/jshint/jshint/pull/3209#issuecomment-344379838

**Comment by jugglinmike** [comment]
@rwaldron Since you merged gh-3215, I re-started the build, and everything is green. Hooray!

**Comment by rwaldron** [comment]
Excellent, again!

**Comment by jugglinmike** [comment]
Thanks, again!

**Pull request merged**
