### PR TITLE
Less ambiguous message for W083

### PR DESCRIPTION
**Pull request by iamlikeme-x**
RE; [#3056](https://github.com/jshint/jshint/issues/3056) -- Make message more relevent and definitive.

### CODE REVIEW

**Comment by jugglinmike** [comment]
Thanks for the path, Oliver! Unfortunately, I can't accept it in its current state because it is failing the build. [The continuous integration service is reporting a linting error due to line length](https://travis-ci.org/jshint/jshint/jobs/173209445). That can be resolved by taking a cue from the other long messages in the file--defining the value as two strings split across two lines and concatenated.

From there, you'll find that this change causes unit tests to fail. We'll have to update the tests accordingly.

Finally, the commit on this branch is not associated with your GitHub account. This is usually caused by a mis-configured git installation, but it makes it difficult to correlate CLA signatures with commits. If you need help fixing this, I'd be happy to give more direction.

Might you be able to follow up with these changes?

**Comment by jugglinmike** [comment]
@iamlikeme-x It's been a week; I'm just wondering if you saw my previous comment.

**Comment by iamlikeme-x** [comment]
Sorry, I saw it at work and forgot to do anything about it — I'm out at the moment but will do this when I get back :)

**Comment by jugglinmike** [comment]
No worries, that happens to me all the time. Glad to hear you're still on board!

**Comment by jugglinmike** [comment]
Checking in again @iamlikeme-x. Still interested in following up on this?

**Comment by iamlikeme-x** [comment]
@jugglinmike any news on updating the tests?

**Comment by jugglinmike** [comment]
The changes to the tests needs to happen in this pull request. Sorry if the phrasing of my comment made that unclear!

**Comment by jugglinmike** [comment]
@iamlikeme-x I'd still like to see this in `master`, but the patch needs to update the unit tests before we can merge it. Do you have any time to make that change? It should be a fairly straightforward find-and-replace operation. (Although looking at this with fresh eyes, I can see we'll also want to fix a typo in the message itself--it needs a space between the words "scoped" and "variable".)

**Comment by jugglinmike** [comment]
@rwaldron followed up with the requested changes, and we merged this to `master` via gh-3149. Thanks!

**Pull request closed without merging**
