### PR TITLE
Fixes: inc/dec and bindings

### PR DESCRIPTION
**Pull request by jugglinmike**
@rwaldron since this updates a few tests, it's going to suffer from conflicts
if gh-3176 is merged first. I'm happy to rebase at that time, but I'm holding
off for now because I don't want to presume that other patch is going to land
at all (since it's a little controversial).

### CODE REVIEW

**Comment by jugglinmike** [comment]
Hm, looks like this fix introduces a kind of regression: it makes JSHint warn that `o["eval"]` is "better written in dot notation." That's true--`o.eval` is valid even in ES3 environments where `o.if` is a SyntaxError. `o.arguments` is likewise valid in all environments.

Still, the conservative thing to do would be to allow that particular form. I'll add a `fixup!` patch to allow those forms (along with a note to remove the allowance in JSHint 3).

**Comment by jugglinmike** [comment]
Alrighty, that "fixup" commit is up!

**Comment by rwaldron** [comment]
And of course I reviewed that one first... Sorry about that

**Comment by jugglinmike** [comment]
No worries; that's the sequence I had in mind. I'll get to rebasing this ASAP.

**Comment by jugglinmike** [comment]
Alrighty, I've rebased, squashed, and force-pushed the result. The original version of this branch is available here:

https://github.com/jshint/jshint/compare/master...jugglinmike:built-ins-3-prebase

**Comment by jugglinmike** [comment]
I've rebased one more time to fix conflicts resulting from today's merge of https://github.com/jshint/jshint/pull/2584

**Comment by jugglinmike** [comment]
Well that was quite a bit trickier than I expected. @rwaldron: to properly satisfy the new tests, I had to re-implement `arguments`. It's for the best, though, since the prior implementation defined `arguments` as a global variable. So the implementation is more technically correct, but there's an observable difference, too: we now catch problems relating to `arguments` being referenced within arrow functions. I've pushed those changes in a "fixup" commit; happy to rebase once you've had a chance to review.

**Comment by jugglinmike** [comment]
This depends on gh-3181, so I'm going to close it until that lands to avoid confusion.

**Comment by rwaldron** [comment]
Hi @jugglinmike! I've landed the blocking PR and re-opened this PR.

**Comment by jugglinmike** [comment]
Okay @rwaldron, I'll admit it. Ever since we saw a string of false positives
from Coveralls, I haven't been paying as much attention the its reports as I
should.  Many of the "uncovered" lines originally reported were actually
covered by Test262 (though I'm thinking about correcting that in the future).
That said, one of the lines was a condition within the `optionalidentifier`
function that this patch made unreachable. By removing it, we're able to remove
a parameter from both `optionalidentifier` and `identifier`. That's done in the
latest `fixup!` commit. An unexpected simplification, and a lesson to pay more
attention to our CI.

**Comment by jugglinmike** [comment]
@rwaldron This should be good to land.

**Pull request merged**
