### PR TITLE
[[FIX]] Add `HTMLCollection` to browser environment.

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**

### CODE REVIEW

**Comment by TheSavior** [comment]
:+1:

**Comment by jugglinmike** [comment]
@nicolo-ribaudo I'd like to move the property higher in the object initializer to maintain the (semi) alphabetical ordering. I'm happy to do this in the process of landing your commit, but I wanted to tell you here so you would have chance to do it yourself (or object) before I do. Let me know!

**Comment by nicolo-ribaudo** [comment]
Travis-ci failed because of coveralls (#2378), can you restart it, please?

**Comment by lukeapage** [comment]
I restarted but coveralls is still down. if you rebase on master, that has a commit in that allows travis to pass even when coveralls fails..

**Comment by jugglinmike** [comment]
Thanks!

**Pull request merged**
