### PR TITLE
[[DOCS]] remove "Good, not Evil" clause from jshint.js license

### LINKED ISSUE #1234: Please change jshint.js license, remove bad or evil
Hi,
could you please modify the jshint.js license to be a real MIT license?

The "The Software shall be used for Good, not Evil." prevents library to be packaged in Debian and maybe other repo where code should really be free of use (yes, even evil). And honestly, if someone wants to use it for evil... well I don't think he will care about the license  :-)

Thanks

Olivier

### PR DESCRIPTION
**Pull request by caitp**
/CC @jugglinmike / @rwaldron I'm not sure if this is safe to do yet, but it probably needs to happen :>

Closes #1234

### CODE REVIEW

**Comment by jugglinmike** [comment]
@caitp The commit message needs some more information that explains the validity of the change. I have a commit ready to go, but I'm waiting to open a pull request until we have the CLA signatures we need. Do you mind if we close this until then?

**Comment by caitp** [comment]
close it, leave it open, tbh I just needed some github activity and am stuck in rietveld land most of the day :p

**Comment by jugglinmike** [comment]
...as in [the Dutch furniture designer](https://en.wikipedia.org/wiki/Gerrit_Rietveld)?

**Comment by caitp** [comment]
https://crrev.com / https://code.google.com/p/rietveld/ that one

**Comment by jugglinmike** [comment]
Oh well is my face red

**Pull request closed without merging**
