### PR TITLE
Fix infinite loop when parsing incomplete functions

### PR DESCRIPTION
**Pull request by grncdr**
See the unit test for the input that would previously cause an infinite loop. I

### CODE REVIEW

**Comment by nicolo-ribaudo** [comment]
Infinite loop?
Using current master branch I haven't any infinite loop.

```
$ bin/jshint - <<< "function"
stdin: line 1, col 1, Missing name in function declaration.
stdin: line 1, col 1, Expected '(' and instead saw ''.
stdin: line 2, col undefined, Unrecoverable syntax error. (100% scanned).

3 errors
```

```
$ bin/jshint - <<< "function what ("
stdin: line 1, col 15, Expected an identifier and instead saw ''.
stdin: line 2, col undefined, Unrecoverable syntax error. (100% scanned).

2 errors
```

**Comment by grncdr** [comment]
Nevermind, this was already fixed on master.

**Comment by grncdr** [comment]
Cross-posted :smile: The issue is there on 2.7.0, seems like a common enough situation to warrant a point-release to npm in my mind.

**Comment by caitp** [comment]
It has been a while since the last release, and there have been a number of fixes since then. We should really publish the next one soon

**Comment by jugglinmike** [comment]
@caitp We're just blocked on gh-2404 . If you could give that a once-over, I'd be happy to release a new version.

**Pull request closed without merging**
