### PR TITLE
[[CHORE]] Update dependencies and change jscs accordingly

### PR DESCRIPTION
**Pull request by BridgeAR**
I checked all tests / build steps etc. and also checked the changelogs for all major / minor versions without any indication that this would break anything.

### CODE REVIEW

**Comment by jugglinmike** [comment]
Thanks for the patch! I appreciate that you did the research to update the project's dependencies, but please understand that this particular task is really a burden of the maintainers. It may take some time before any of us are able to conduct a thorough review for this changeset.

**Comment by BridgeAR** [comment]
Shall I split this into smaller patches? E.g. the dev dependencies should not be an issue? And I could also add the changelog for the other three dependencies if that helps or check the commits for things that changed, if you trust me on that.

**Comment by jugglinmike** [comment]
I don't think that will be necessary. Thanks, though!

**Comment by jugglinmike** [comment]
I'm closing this because the dependency information no longer reflects the latest versions of the modules we're using. When we update dependencies, we'll need to use the latest versions.

**Pull request closed without merging**
