### PR TITLE
[[FIX]] Allow semicolon as string value in JSON

### PR DESCRIPTION
**Pull request by jugglinmike**
Resolves gh-2488

Commit message:

> Previously, any token with the value ";" would trigger JSHint to lint
> the input as though it were JavaScript code. Because the token value may
> also describe a string, this caused JSHint to incorrectly interpret JSON
> input as JavaScript in some cases.
>
> Ensure that only semicolon tokens parsed as punctuators trigger
> JavaScript parsing.
>
> This change necessitated modifying an existing test. That test was
> authored to ensure that JSHint would halt on invalid input and report
> the input as invalid. The modified version of the test continues to
> assert that, but the specific errors have changed because JSHint now
> interprets the input as invalid JSON (not invalid JavaScript).

### CODE REVIEW

**Comment by caitp** [comment]
LGTM, but we do have a utility function for that

**Comment by jugglinmike** [comment]
Yeah, but it really irks me to create a new array literal every time. Maybe consistency trumps my unsupported insistence on "efficiency" in JavaScript.

**Comment by jugglinmike** [comment]
@caitp I took your advice, and thought you might be interested: in my original patch

```diff
@@ -4511,7 +4511,7 @@ var JSHINT = (function() {
           break;
         }
       }
-      if (pn.value === ";") {
+      if (pn.type === "punctuator" && pn.value === ";") {
         ret.isBlock = true;
         ret.notJson = true;
       }
```

`pn.type` will never be "punctuator". ["(punctuator)", on the other hand...](https://github.com/jshint/jshint/blob/a4f4bf4319186480778f7b75ef74382a88428e99/src/jshint.js#L4614)

**Comment by caitp** [comment]
Yeah I don't have that stuff committed to memory. I think 'id' might be the one we want, I'd check the helper function to be sure

**Comment by jugglinmike** [comment]
Oh, I was just saying that I used the wrong value, and that the error would have been avoided if I had just used the utility function in the first place. It should be good now

**Comment by nicolo-ribaudo** [comment]
> Yeah, but it really irks me to create a new array literal every time

[You can use a string](https://github.com/lodash/lodash/blob/master/lodash.js#L6547):
```js
checkPunctuators(pn, ";");
```

**Comment by lukeapage** [comment]
It would be inconsistent and somone might use it with e.g. `... ` where it would appear to work. Better to modify the function to take multiple arguments? You might be able to use indexof and skip the first item in arguments to make it elegant iniside the check function too..

**Comment by caitp** [comment]
if it's a string, it should really be just a `return type === '(punctuator)' && id === theParticularPunctuatorWeCareAbout` which is a pretty trivial change to make in the helper

**Comment by lukeapage** [comment]
will merge and make a new pr for @caitp's suggestion

**Comment by lukeapage** [comment]
committed https://github.com/jshint/jshint/commit/0bda42297e435d16b9a244be72b69b1462077d5d and https://github.com/jshint/jshint/commit/ab73e010677ad6c34e21b8854fd5a43f7f1ca766

**Pull request closed without merging**
