### PR TITLE
Version 2.13.0

### PR DESCRIPTION
**Pull request by jugglinmike**
This is a tracking branch for the next minor release of JSHint. If you'd like
to implement a new feature, this is the place to submit it!

ES2020 features:

- [x] [Dynamic import](https://github.com/tc39/proposal-dynamic-import)
- [x] [`import.meta`](https://github.com/tc39/proposal-import-meta)
- [x] [BigInt](https://github.com/tc39/proposal-bigint)
- [x] [`globalThis`](https://github.com/tc39/proposal-global)
- [x] [Optional chaining](https://github.com/tc39/proposal-optional-chaining)
- [x] [Nullish coalescing](https://github.com/tc39/proposal-nullish-coalescing)
- [x] [`export * as ns from "mod"`](https://github.com/tc39/ecma262/pull/1174)

### CODE REVIEW

**Comment by jugglinmike** [comment]
I've updated the description with a list of ES2020 features that are relevant for JSHint.

**Comment by jugglinmike** [comment]
[We published the project license change using version 2.12.0](https://jshint.com/blog/2020-08-02/release-2-12-0/), so I'm updating this pull request to describe 2.13.0 instead.

**Comment by jugglinmike** [comment]
Rebased on top of the `master` branch

**Comment by jugglinmike** [comment]
We've landed a bunch of bug fixes to the `master` branch, particularly ones that will help implement dynamic import in this branch. Although traditional git workflows would call for merging `master` into this feature branch, I've chosen to rebase. That keeps this history clean, and since no one else is working from this branch (to the best of my knowledge), there's little risk of disruption that's typical in rebase operations.

[I've pushed the prior version of this branch to my fork of the repository](https://github.com/jshint/jshint/compare/master...jugglinmike:v2.12.0-2021-02-28?expand=1) in case that's helpful.

**Comment by RedGuy12** [comment]
Any ETA?

**Comment by almercier** [comment]
@jugglinmike With Optional chaining merged, is this ready to go out of draft now?

**Comment by jugglinmike** [comment]
@almercier Yes!

@rwaldron You've already reviewed everything in this branch, so no further action required here. That said, it would be nice to get gh-3541 in for the next release. Would you mind taking a look at that?

**Comment by shmolf** [comment]
I'm very much looking forward to see this available in my development environment. Will this be approved and merged anytime soon, so as to make it into the next tagged version?

**Comment by almercier** [comment]
@jugglinmike @rwaldron It's been about a month since any update on this, do you have an estimated timeline on when this could be released?

**Pull request merged**
