### PR TITLE
Fix for gh-3013

### PR DESCRIPTION
**Pull request by jugglinmike**
@rwaldron This is a fix for gh-3013 in two parts. You can see my response to
that issue for more detail about the problem. Please review carefully because
I'm messing with some relatively fundamental behavior here.

One specific question I have for you: I do not think it's possible to test for
this behavior at every call site of `nextLine`. (The situation we're interested
in here is when the lexer is tokenizing input and may pass over a `-W100`
directive.) I've still updated the call sites for consistency, and in case some
future change *can* use `checks` from different call sites. Does that seem
right to you?

### CODE REVIEW

**Comment by jugglinmike** [comment]
@rwaldron Also note that a much simpler fix would be to remove `W100` altogether--I still don't know exactly what that warning is for. Check out gh-2741 for an unresolved discussion along these lines.

**Comment by jugglinmike** [comment]
This needs work--W101 is also suffering the same problem.

**Comment by jugglinmike** [comment]
@rwaldron Thanks to gh-3017, I have a better understanding of the scope of this problem.
The bug concerns all warnings that are detected by the lexer, namely W048,
W049, W100, W101, W113, and W119. An unrelated bug fix that was released with
version 2.9.3 exposed the problem to a wider category of input. (I suppose that
still qualifies as a "regression," but we may be splitting hairs there.)

The context that triggers this error is the lookahead operations JSHint
performs to disambiguate between multiple valid parsing strategies:

- the `{` token in an expression position (either an object literal or a
  destructuring assignment)
- the `[` token (either an array literal or a destructuring assignment)
- the `(` token (either a grouping operator or an arrow function parameter
  list)

This latest version of the patch addresses all lexer-triggered warnings in all
relevant contexts. In the interest of transparency, I've pushed up the new
version of the patch as a `fixup!` commit. Before this lands, I'd like to
squash with a new commit message that correctly describes the expanded scope of
the fix.

> [[FIX]] Honor "ignore" directives during lookahead
>
> When the lexer emits a token, it may not be aware of the complete set of
> in-line linting directives because these are activated by the parser. This
> is notably the case during parsing lookahead operations (e.g. when selecting
> between multiple parsing strategies that may follow the `{`, `[`, and `(`
> tokens).
>
> In these contexts, the lexer should not immediately report token-related
> warnings. Reporting must be deferred until the parser has visited all preceding
> comments and fully applied all linting directives present in the source
> code.

I've also included the above text as a comment within the test's fixture file.
That file necessarily contains a few instances of non-printable characters,
which has the unfortunate side-effect of suppressing its output in patch
summaries from git and GitHub.com.

@damyanpetev @batista would either of you mind testing this branch of JSHint
against your code base and verifying that it resolves your issue?

**Comment by batista** [comment]
Sure, I'm unable to do it now, but I'll test it and get back to you
tomorrow.

On Sep 10, 2016 21:03, "jugglinmike" <notifications@github.com> wrote:

@rwaldron <https://github.com/rwaldron> Thanks to gh-3017
<https://github.com/jshint/jshint/issues/3017>, I have a better
understanding of the scope of this problem.
The bug concerns all warnings that are detected by the lexer, namely W048,
W049, W100, W101, W113, and W119. An unrelated bug fix that was released
with
version 2.9.3 exposed the problem to a wider category of input. (I suppose
that
still qualifies as a "regression," but we may be splitting hairs there.)

The context that triggers this error is the lookahead operations JSHint
performs to disambiguate between multiple valid parsing strategies:

   - the { token in an expression position (either an object literal or a
   destructuring assignment)
   - the [ token (either an array literal or a destructuring assignment)
   - the ( token (either a grouping operator or an arrow function parameter
   list)

This latest version of the patch addresses all lexer-triggered warnings in
all
relevant contexts. In the interest of transparency, I've pushed up the new
version of the patch as a fixup! commit. Before this lands, I'd like to
squash with a new commit message that correctly describes the expanded
scope of
the fix.

[[FIX]] Honor "ignore" directives during lookahead

When the lexer emits a token, it may not be aware of the complete set of
in-line linting directives because these are activated by the parser. This
is notably the case during parsing lookahead operations (e.g. when selecting
between multiple parsing strategies that may follow the {, [, and (
tokens).

In these contexts, the lexer should not immediately report token-related
warnings. Reporting must be deferred until the parser has visited all
preceding
comments and fully applied all linting directives present in the source
code.

I've also included the above text as a comment within the test's fixture
file.
That file necessarily contains a few instances of non-printable characters,
which has the unfortunate side-effect of suppressing its output in patch
summaries from git and GitHub.com.

@damyanpetev <https://github.com/damyanpetev> @batista
<https://github.com/batista> would either of you mind testing this branch
of JSHint
against your code base and verifying that it resolves your issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/jshint/jshint/pull/3016#issuecomment-246126241>, or mute
the thread

**Comment by jugglinmike** [comment]
Thanks!

**Comment by rwaldron** [comment]
I can review tomorrow—please nudge me if I haven't reported by noon

**Comment by batista** [comment]
@jugglinmike can confirm that 72209ba95dde23bb2b19912a36c713f5e475d9e6 fixes #3017 for me

**Comment by jugglinmike** [comment]
Thanks, Sérgio!

**Comment by rwaldron** [comment]
@jugglinmike I'm confused about the relationship to https://github.com/jshint/jshint/issues/2741

**Comment by jugglinmike** [comment]
@rwaldron I made that comment when I believed that the bug reported in gh-3013 was limited to W100. From that perspective, another viable fix was to remove W100 altogether--I suggested that as a possibility in gh-2741.

While I still don't understand the intent of W100, it's clear that the underlying problem is more far-reaching, so I'm happy to let the conversation about removing W100 proceed separately.

**Comment by damyanpetev** [comment]
@jugglinmike A bit late, but I can also verify 72209ba95dde23bb2b19912a36c713f5e475d9e6 honored the ignore for W100 warning with as initially logged in #3013 (massive IIFE). Also tested with this bit:
```js
(function() {
	var test;
    /*jshint -W100 */
    test = "‏س";
})();
```
And it worked out okay as well.

**Comment by rwaldron** [comment]
Thanks @damyanpetev and @batista, you're testing and confirmation is helpful here

**Comment by rwaldron** [comment]
Create work here, thanks @jugglinmike

**Pull request merged**
