### PR TITLE
Correct reporting of early "param" references

### PR DESCRIPTION
**Pull request by jugglinmike**

### CODE REVIEW

**Review by rwaldron — APPROVED** [review]
The number of expected failures this eliminates is astonishing.

**Comment by rwaldron** [comment]
@jugglinmike can you resolve the conflicts? Thanks!

**Comment by jugglinmike** [comment]
> The number of expected failures this eliminates is astonishing.

Yeah. Test262's test generation tool can make for some pretty satisfying fixes.

> @jugglinmike can you resolve the conflicts? Thanks!

All set!

**Review by rwaldron — APPROVED** [review]
Re-review

**Pull request merged**
