### PR TITLE
Default params

### PR DESCRIPTION
**Pull request by jugglinmike**
@lukeapage Rebasing your branch from gh-2493 involved resolving merge conflicts in one of your commits (resulting from 87378cca3c98e1ff4d5be11f6c16a9f24a212e3e). Since both of the conflicted commits are yours, I'd appreciate it if you could give this resolved version one final review before we merge it.

### CODE REVIEW

**Comment by jugglinmike** [comment]
...or (and this is probably even better), re-do the conflict resolution yourself and force-push to your branch at gh-2493.

**Comment by lukeapage** [comment]
> ...or (and this is probably even better), re-do the conflict resolution yourself and force-push to your branch at gh-2493.

Done. I squashed and changed the commit message. Reviewing this PR, I am fairly certain we resolved in the same way.

**Comment by jugglinmike** [comment]
Thanks!

**Comment by jugglinmike** [comment]
You are correct, by the way:

```diff
$ git diff origin/default-params lukeapage/default-params
diff --git a/src/jshint.js b/src/jshint.js
index 406ecec..f0aac82 100644
--- a/src/jshint.js
+++ b/src/jshint.js
@@ -2956,7 +2956,7 @@ var JSHINT = (function() {
         classExprBinding ? "class" : "function", state.tokens.curr, false);
     }
 
-    // create the param scope and adds the labels to it
+    // create the param scope (params added in functionparams)
     state.funct["(scope)"].stackParams(true);
 
     var paramsIds = functionparams(options);
diff --git a/tests/unit/options.js b/tests/unit/options.js
index d2775f4..e36adbb 100644
--- a/tests/unit/options.js
+++ b/tests/unit/options.js
@@ -907,6 +907,7 @@ exports['unused with param destructuring'] = function(test) {
     .addError(8, "'args' is defined but never used.")
     .test(code, { esnext: true, unused: "strict" });
 
+
   test.done();
 };

```

**Pull request closed without merging**
