### PR TITLE
[[CHORE]] Complete Lodash update

### PR DESCRIPTION
**Pull request by jugglinmike**
A previous commit modified the project's usage of Lodash in preparation
to update to a new major release of that library. That commit mistakenly
omitted the necessary modification for the `package.json` file. Complete
the dependency update by modifying the version specifier in that file.

### CODE REVIEW

**Comment by vladikoff** [comment]
Thank you !

**Comment by vladikoff** [comment]
@jugglinmike can anyone else review this?

**Comment by jugglinmike** [comment]
Indeed they can. @caitp mind taking a look?

(Pardon the delay; TC-39 met last week, and that generally soaks up all of our attention.)

**Comment by morfie78** [comment]
What is the status of this, and is there a timeline of when npmjs will be updated with this change?  Thanks!

**Comment by vladikoff** [comment]
Needs rebase

**Comment by EricHanLiu** [comment]
Any update here?

**Comment by vladikoff** [comment]
Thanks Rick!

**Comment by morfie78** [comment]
Very excited. Thank you!

**Comment by kamronbatman** [comment]
Thank you for doing this.
I would love to see a new published version so we the npm audit goes away for several of my dependencies.

**Pull request merged**
