### PR TITLE
Fix stdin code don't check jshintignore

### PR DESCRIPTION
**Pull request by CatTail**

### CODE REVIEW

**Comment by rwaldron** [comment]
- Need more info on this (explanatory details, background, usecase, etc)
- Please rebase

**Comment by CatTail** [comment]
When used in git hook, jshint will check the changed content by `jshint --filename <some file name>`.

But there are cases that certain file should be ignored, which means stdin should support ignore logic

**Comment by lukeapage** [comment]
This would be a breaking change.

To specify configuration for stdin, you need only use the `-c` option. I've just tested that it works..

```
$ cat test.js | jshint -c jshint/.jshintrc -
```

**Comment by lukeapage** [comment]
related issue asking for this feature: https://github.com/jshint/jshint/issues/2170

**Comment by jugglinmike** [comment]
Actually, I don't believe this to be a breaking change--it can only make JSHint
pass in more cases. @rwaldron: are you satisfied with the explanation shared
earlier?

@CatTail This pull request has been sitting around for a while--sorry about
that. I'm happy to rebase and add tests, but we will definitely need your
signature on our CLA before we can move forward. Would you mind signing? It
should only take a moment!

**Comment by CatTail** [comment]
@jugglinmike Just signing CLA.

**Comment by jugglinmike** [comment]
Thanks for the signature, @CatTail! I've rebased, resolved the conflict, updated the message to satisfy our [contribution guidelines](https://github.com/jshint/jshint/blob/540ed85f075f7ae1317a37447c9fe9644e0d62e4/CONTRIBUTING.md#header) and merged at commit d4f83a4c422a4f491e8e6da347c68da2869e1acf. (Followed up with a commit another commit containing a unit test: 0938dc70f65726973f05cdab8a6772e9ade47080.) Sorry for the delay; I'm glad to finally have this landed!

**Pull request closed without merging**
