### PR TITLE
Fix issue #1825: use of `!` with `instanceof` should require parentheses

### PR DESCRIPTION
**Pull request by julienw**

### CODE REVIEW

**Comment by rwaldron** [comment]
LGTM

@caitp @jugglinmike ?

**Comment by caitp** [comment]
looks good to me, I'm surprised this wasn't already happening =) genuinely shocked

**Comment by rwaldron** [comment]
Probably because Crockford wasn't using `new` and so never really used the code pattern that this would most likely appear in, therefore never considered :)

**Comment by caitp** [comment]
so, the only thing is, it's possible this will break peoples builds --- there's a trivial workaround, but it's not very nice to ship something like that in a patch release.

Maybe, this error should get its own message to at least make it obvious how to fix any build failures that it triggers (and give it its own relaxation option to turn it off)

**Comment by rwaldron** [comment]
> so, the only thing is, it's possible this will break peoples builds --- there's a trivial workaround, but it's not very nice to ship something like that in a patch release.

> Maybe, this error should get its own message to at least make it obvious how to fix any build failures that it triggers (and give it its own relaxation option to turn it off)


Nice catch :)

**Comment by julienw** [comment]
I'm in holidays for 1 week (the kind of holidays without a computer) so feel free to take it from here :)

**Comment by julienw** [comment]
> so, the only thing is, it's possible this will break peoples builds --- there's a trivial workaround, but it's not very nice to ship something like that in a patch release.

If this shipped in a minor release instead, would it be ok ?

**Comment by caitp** [comment]
@julienw npm would still pull it in when people use the hat operator (like `^2.6.3` in package.json).

Maybe we could merge this and I could add some quick fixes to it tonight?

**Comment by julienw** [comment]
ok, I get it: minor versions include only backward compatible changes, and this is not one.

This is not that urgent, this is waiting for several months, so I can do the needed change when I come back if necessary. No need to rush.

In case you intend to do a major version this week, feel free to merge :p

**Comment by julienw** [comment]
\o/ thanks. And sorry for not taking the time to fix the comments ..

**Pull request merged**
