### PR TITLE
Update cli.js

### PR DESCRIPTION
**Pull request by meh-uk**
Update cli.js so that the exclude option supports multiple (comma separated) files.

### CODE REVIEW

**Comment by lukeapage** [comment]
@meh-uk 

I don't have any problem with the extra functionality, but since it is a new feature, not a bugfix, I'll await a member of the core team to give their opinion.

However, if they have no problems, we also need the CLA to be signed.. it should only take a moment:

https://www.clahub.com/agreements/jshint/jshint

Thanks.

**Comment by jugglinmike** [comment]
Let's wait for the next minor on this (adding the "proposal" label to document this). In the meantime, @meh-uk: would you be up for adding a test? If not, I'd be happy to help out.

**Comment by meh-uk** [comment]
I probably could add a test but I'm on holiday this week. What's the ETA of the next minor version?

**Comment by lukeapage** [comment]
There is no plan,  i imagine you will have time!

**Comment by meh-uk** [comment]
@jugglinmike I've added a test this afternoon, let me know if you need me to do anything else :).

**Comment by jugglinmike** [comment]
Wonderful! We'll include this in the next minor release. Thanks, Matthew!

**Comment by jugglinmike** [comment]
I was hoping to be slightly more rigorous about when/how we land feature additions into `master`, but as you've pointed out, it's really too late for that. Feel free to merge!

**Comment by lukeapage** [comment]
committed to master - https://github.com/jshint/jshint/commit/bd4ec2514b5c2a5ea49688b4a6724091ee4bfdde, thanks

**Comment by meh-uk** [comment]
Thanks

**Pull request closed without merging**
