### PR TITLE
Improve E031, "Bad assignment."

### PR DESCRIPTION
**Pull request by jugglinmike**
A couple patches to improve the detection and reporting of the "Bad assignment" error. I've included more detail in the commit messages.

### CODE REVIEW

**Comment by jugglinmike** [comment]
I just pushed up another related fix.

**Comment by rwaldron** [comment]
@jugglinmike This is a really smart set of changes—great work identifying this and addressing it so cleanly.

**Comment by jugglinmike** [comment]
Thanks, @rwaldron! I've fixed the typos you identified in the second commit message.

**Comment by rwaldron** [comment]
Thanks @jugglinmike !

**Pull request merged**
