### PR TITLE
[[FIX]] `latedef` shouldn't warn when marking a var as exported

### LINKED ISSUE #2662: Exported var was used before it was defined in 2.9.0
Using JSHint 2.9.0, I get this error:  `common-lib.js: line 2, col 5, 'commonLib' was used before it was defined.` and in previous versions of JSHint I did not.  Moving the `/* exported ... /*` line to the end of the file resolves the symptom.  Here is a minimum sample repro project:

.jshintrc:
```
{
  "latedef": true
}
```

common-lib.js:
```
/* exported commonLib */
var commonLib = (function () {
  'use strict';

  return 'the common lib';
}());
```

command I run:
`jshint .`

### PR DESCRIPTION
**Pull request by nicolo-ribaudo**
Fixes #2662

### CODE REVIEW

**Comment by lukeapage** [comment]
I would add a new test run with latedef option to the exported test.

**Comment by lukeapage** [comment]
I considered this approach but I wasn't sure the exported directive always means global scope.. I've been thinking though and I can't think of an example of non global leader scope so maybe that's ok.

**Comment by lukeapage** [comment]
does this work if the directive is after the declaration? did it work in 2.8?

**Comment by nicolo-ribaudo** [comment]
> does this work if the directive is after the declaration? did it work in 2.8?

Yes - yes

**Comment by lukeapage** [comment]
ah yes, but only if the directive is in the global scope. why not just check the global scope rather than only doing it if current is global? or..  wdyt?

**Comment by lukeapage** [comment]
because that wouldn't work with a var in an if block...  ok.

**Comment by nicolo-ribaudo** [comment]
> because that wouldn't work with a var in an if block... ok.

It works:
```js
// jshint unused: strict, esversion: 6
if (true) {
  /*exported a, b*/
  let a; // `a` is defined but never used - which is ok, because `a` *isn't* really exported
  var b;
}
```

**Comment by lukeapage** [comment]
yes sorry for the brief comments, away from computer again.. thats what i
meant,  I was answering my own question.

**Comment by lukeapage** [comment]
one small not very important regression remaining is code like this...

```
// jshint unused: true

function foo() {
}

if (true) {
   /* exported foo */
}
```

which doesn't fail at the moment because peeking means the lexer runs the directive before entering the block - that may and probably will change. However this does fail at the moment...

```
// jshint unused: true

function foo() {
}

if (true) {
    for(var i = 0; i < 1; i++) {
       // dont peek
    }
   /* exported foo */
}
```
I'm not sure if there are any realistic examples of this.

To fix it, instead of...

```
 } else if (_current["(type)"] === "global" && _.has(_current["(labels)"], labelName)) {
```

you would have to use _getLabel but tell it to only look in the global scope.. I'm not sure it is worth it.

**Comment by lukeapage** [comment]
`_addUsage` can be inlined since it is now only used in one place.

**Comment by lukeapage** [comment]
> > I would add a new test run with latedef option to the exported test.

> Added

Great, that covers that. For extra coverage though, how about..

here - https://github.com/nicolo-ribaudo/jshint/commit/a58a91b8ca7e18e19822a721c32aecdb8989d8b8#diff-59929b5758a2716d37551959b0155cbaR1126

could you also add

```
run.test(src, {latedef: true, unused: true });
```

**Comment by nicolo-ribaudo** [comment]
Done

**Comment by lukeapage** [comment]
The trouble with that fix is that I don't think this works

```
// jshint unused: true
if (true) {
  var a;
}
/* exported a */
```

again I'm not sure how important these corner cases are...

**Comment by nicolo-ribaudo** [comment]
> The trouble with that fix is that I don't think this works

Fixed

**Comment by lukeapage** [comment]
Thanks, LGTM

**Comment by lukeapage** [comment]
@jugglinmike I don't mind merging this but I'll keep it around till you comment in case you have any other observations. If you want to merge it, go ahead of course!

**Comment by jugglinmike** [comment]
@lukeapage I've been watching this patch come together, and it looks good to me. I'll let you do the honors since the scope manager is your baby (figuratively).

**Comment by lukeapage** [comment]
squashed and committed - https://github.com/jshint/jshint/commit/c630994e9470bd82d704aba05a0ece07d1582147

**Pull request closed without merging**
