### PR TITLE
Update appveyor.yml.

### PR DESCRIPTION
**Pull request by XhmikosR**
* Add Node.js 0.11 like Travis is using.
* Remove global cache since we don't install any global modules.

### CODE REVIEW

**Comment by XhmikosR** [comment]
I still believe this should go in ASAP; there are tests failing with node.js 0.11 on Windows.

**Comment by caitp** [comment]
@rwaldron / @jugglinmike do you guys know if appveyor has an "allowed failures" setting? I'd be okay with landing this if we can let win builds get away with failing until the bugs are fixed**

**Comment by XhmikosR** [comment]
@caitp: https://github.com/jshint/jshint/pull/2086#issuecomment-70116568

So, I can add that, but I doubt it will help since everyone will forget about those failures unless the whole build is marked as failed...

**Comment by caitp** [comment]
people who care about windows + node 0.11 support will pay attention to the failures --- otherwise it makes working on other stuff much more problematic

**Comment by XhmikosR** [comment]
Well, the whole point of testing is to see issues. And testing 0.11 ensures everything will work in the next node.js major version.

So my suggestion would be to fix the issues instead of hiding it.

**Comment by XhmikosR** [comment]
But anyway, I can add the changes to allow 0.11 not to fail if you want that. Just ping me and I'll update the PR.

**Comment by caitp** [comment]
i've already asked for that

**Comment by XhmikosR** [comment]
Well you asked the others not me.

**Comment by XhmikosR** [comment]
Done.

**Comment by XhmikosR** [comment]
Updated. The node.js 0.11 issues are fixed with node.js 0.11.15.

CC @FeodorFitsner any chance you update to that?

**Comment by FeodorFitsner** [comment]
Oh, there were two 0.11.x releases recently: 14 and 15. Yeah, will deploy today/tomorrow as well as latest io.js 1.0.3. Thanks for letting me know.

**Comment by XhmikosR** [comment]
Thanks! Please ping me when 0.11.15 is live since I can simplify this PR.

**Comment by FeodorFitsner** [comment]
Sure!

**Comment by FeodorFitsner** [comment]
Node.js 0.11.15 and io.js 1.0.3 have been deployed to all build worker images.

**Comment by XhmikosR** [comment]
Thanks! Works fine now.

**Pull request closed without merging**
