### PR TITLE
[[FIX]] Allow invoking result of optional chaining

### PR DESCRIPTION
**Pull request by jugglinmike**
This should resolve gh-3551.

### CODE REVIEW

**Review by rwaldron — APPROVED** [review]

**Comment by ehoogeveen-medweb** [comment]
Does this also fix the warning `Expected an assignment or function call and instead saw an expression. (W030)` for expressions like `obj.func?.()` ("call this function if it exists")? It seems odd to me that `obj.func()` is allowed as an expression but `obj.func?.()` isn't.

**Comment by jugglinmike** [comment]
@ehoogeveen-medweb That behavior isn't related to this fix. Your expectation seems logical to me, though, so I'll write a patch for that, too.

**Comment by jugglinmike** [comment]
Here's the patch: gh-3557

**Comment by jugglinmike** [comment]
[We released both fixes in JSHint version 2.13.1.](https://jshint.com/blog/2021-08-10/release-2-13-1/)

**Pull request merged**
