### PR TITLE
Fixes markdown syntax

### PR DESCRIPTION
**Pull request by torn4dom4n**
I fix some markdown syntax.

### CODE REVIEW

**Comment by jugglinmike** [comment]
Thanks for the patch! The "footnote" syntax is not recognized by the project website's Markdown processor, so it won't have the intended effect. Could you remove those changes?

**Comment by torn4dom4n** [comment]
The `relicensing-2020.md` is not recognized but the changes easy to observe. I think it is necessary.

**Comment by jugglinmike** [comment]
Please do. The website build system will not produce the intended markup from a file which uses that syntax.

**Comment by torn4dom4n** [comment]
@jugglinmike I reverted changes in the `relicensing-2020.md`

**Comment by jugglinmike** [comment]
Thanks!

**Pull request merged**
