### PR TITLE
[[FEAT]] Use conventional-github-releaser

### PR DESCRIPTION
**Pull request by stevemao**

### CODE REVIEW

**Comment by jugglinmike** [comment]
Thanks for the patch! I think I prefer the host-agnostic "conventional-changelog" module you originally proposed in gh-2581. I'd like to check the changelog in to the project for discoverability. We could then parse that file to generate blog posts on jshint.com for each release. What do you think?

**Comment by jugglinmike** [comment]
(Doing that would address an open issue against this project: gh-2331.)

**Comment by stevemao** [comment]
Yeah, of course! I didn't know you guys already have issues with changelog but I think it can address those :)

**Comment by stevemao** [comment]
Done. A quick link to the generated changelog
https://github.com/stevemao/jshint/blob/changelog/CHANGELOG.md

**Comment by jugglinmike** [comment]
Thanks Luke. Care to comment?

**Comment by lukeapage** [comment]
> Thanks Luke. Care to comment?

No, I don't really have any comments ?

**Comment by jugglinmike** [comment]
@stevemao I've been playing with this locally, and there's just one last thing I'd like to confirm. It seems as though, configured in this way, the tool will insert new entries into the changelog only (in other words, it will not re-generate the existing log). I think this is ideal, because it would allow for manual entry of commentary that is not defined in the project history. (As stated above, I want to re-use the generated file to create pages on http://jshint.com/blog/ , and I'll be starting by manually inserting the content of existing blog posts into the `CHANGELOG.md` file.)

Is this correct? Do you know if anyone is currently using the tool in combination with manual modification of the file?

**Comment by stevemao** [comment]
I didn't manually generate the logs
`conventional-changelog -p jshint -i CHANGELOG.md -w -r 0`
and
`conventional-github-releaser -p jshint -r 0`

**Comment by stevemao** [comment]
This is why I regenerated the logs for you for the first time. Of course you could do that by yourself :)

**Comment by jugglinmike** [comment]
Sorry, I didn't explain myself properly. Let me put it another way:

If we accept this change, then I will obviously want to use the tool to update the `CONTRIBUTING.md` file when it comes time to release JSHint 2.9.0. After I do that, is it "safe" for me to manually edit that file, adding some additional notes for the release that were not automatically inserted?

I ask because the tool could have been built in such a way that the entire changelog file is re-created every time it is run. If that were the case, I would lose all the manual editions when I released the *next* version of JSHint (2.9.1, for example).

Testing locally, it looks like this is not how the tool works. In other words, it should be "safe" to insert manual additions because the tool only inserts new content. I just wanted to verify this with you because this will be an important part of how I would like to maintain the changelog.

**Comment by stevemao** [comment]
This is correct :) 

Longer answer: We don't want user to lose their previous manually edited logs too unless you do `conventional-changelog -p jshint -i CHANGELOG.md -w -r 0`
For `conventional-github-releaser` it will never overwrite any release. You have to delete first then make a new one.

**Comment by stevemao** [comment]
BTW, `conventional-changelog` and `grunt-conventional-changelog` projects themselves are doing this way. We always leave previous generated logs. We sometimes add some entries in them too.

**Comment by jugglinmike** [comment]
Perfect! I've landed this with some modifications to the commit subject lines (using "DOCS" and "CHORE" as described by the project's contribution guidelines). I followed up by [removing the old changelog script](https://github.com/jshint/jshint/commit/c59ce02f4ec4c77fcc499350faa070a1cb43936d) and [importing additional changelog content from jshint.com](https://github.com/jshint/jshint/commit/d4db77129e4f6daf74a944ab3b83af05c2c891a5). Thanks a bunch, Steve--this is a much-needed improvement to our process and documentation!

**Comment by stevemao** [comment]
Thanks @jugglinmike

**Pull request closed without merging**
