### PR TITLE
Use `path.join` properly and in more places.

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @caitp

### CODE REVIEW

**Comment by XhmikosR** [comment]
Updated one more time...

**Comment by XhmikosR** [comment]
Bump.

Is anyone still interested in my PRs? Or should I drop them?

**Comment by jugglinmike** [comment]
I'm still reluctant to make this change for the same reasons I cited when you initially proposed it: https://github.com/jshint/jshint/pull/1932 .

Restating: this change (and also gh-2298) is not motivated by a real-world problem. While I think your commitment to propriety is commendable, project maintainers have to balance the benefits of refactoring against concerns for stability. Please understand we have a responsibility to keep things stable (even though we may not like certain aspects of the code base, either!).

For instance, you can see how a seemingly-innocuous change like 2fc1e2377ac590eb0455f0a2b0ffef76f3f0b0ef caused actual problems without adding any value to the project itself: https://github.com/jshint/jshint/issues/2330 . I very much regret this and want to avoid situations like these whenever possible.

I can't speak for the other maintainers, though.

**Comment by XhmikosR** [comment]
Well,  this change has nothing to do with the one you linked. In fact, this
is the proper way. Not said by me,  just check node docs.

Secondly, tests pass just fine plus I've tested this thoroughly.

Thirdly,  I was referring to all my PRs not this one only.

Don't get me wrong, but you are overthinking this specific patch.

**Pull request closed without merging**
