### PR TITLE
Don't emit E048 when declare let in nested block without curly bracket. ...

### PR DESCRIPTION
**Pull request by gintau**
...Fixes gh-1862

### CODE REVIEW

**Comment by lukeapage** [comment]
@gintau Please could you sign the cla? It only takes a moment.
https://www.clahub.com/agreements/jshint/jshint

Thanks for the contribution.

The code looks good. I would maybe add a comment (explaining why you exclude the next token is a for loop), but if you don't have time I can add that.

**Comment by gintau** [comment]
Hi Luke,

This pull request is created for a long time, I may need time to pickup
what's going on there.
So please add any comment you think it's appropriate.

Thanks,
Tony

2015-06-20 9:13 GMT-07:00 Luke Page <notifications@github.com>:

**Comment by lukeapage** [comment]
Thanks

**Comment by lukeapage** [comment]
merged: https://github.com/jshint/jshint/commit/a8fc16b40620de503ef67bd9920bb10218ab2714

**Pull request closed without merging**
