### PR TITLE
[[DOCS]] Add details relating to CLA

### PR DESCRIPTION
**Pull request by jugglinmike**

### CODE REVIEW

**Comment by caitp** [comment]
so does the google doc tie into github's cla machinery? or is it gonna be awkward :<

**Comment by jugglinmike** [comment]
It's gonna be awkward, CLAHub just doesn't have the functionality to make it a viable option.

I'm sorry about that, but I really did try to streamline the process: https://github.com/clahub/clahub/pull/97 . There's been no response from the maintainers for that pull request for a week, though. Maybe a little more patience is in order, but we have a fair amount of interest in gh-1234, and I hate to keep putting this off.

**Comment by caitp** [comment]
you might have some luck if you tweet at one of the committers of that repository, or at @github themselves. That __may__ help get things noticed.

**Comment by jugglinmike** [comment]
I'm reluctant to do that because it usually feels like pestering to me. Maybe after a week it's okay? https://twitter.com/JugglinMike/status/559440667425124352

**Comment by jasonm** [comment]
Unresponsive maintainer checking in - sorry for the radio silence!  just got back to work last week after being out of the country for a month so I missed these notifications while wading through and triaging my email backlog.  Thanks for the tweet!

**Pull request merged**
