### PR TITLE
Update dependencies.

### PR DESCRIPTION
**Pull request by XhmikosR**
/CC @caitp

### CODE REVIEW

**Comment by XhmikosR** [comment]
Updated.

Newer underscore.js seems to work fine now. Note that jscs might need some rules tweaking after this is merged.

**Comment by caitp** [comment]
I mean if travis passes it looks okay to me, but I recall rick saying he wanted to replace underscore with lodash at some point

**Comment by XhmikosR** [comment]
Yeah, tests failed a few weeks ago with underscore 1.7.0, but now everything is fine.

**Comment by caitp** [comment]
@rwaldron / @jugglinmike do you guys know if appveyor has an "allowed failures" setting? I'd be okay with landing this if we can let win builds get away with failing until the bugs are fixed

**Comment by XhmikosR** [comment]
@caitp: this doesn't fail, it's #2084 that reveals the node.js 0.11 issues. And yes, I can change it so that we allow 0.11 to fail if you want.

**Comment by caitp** [comment]
I meant to post this on the PR which adds the appveyor 0.11 tests

**Comment by caitp** [comment]
you have too many prs open, it's hard to keep track ;)

**Comment by XhmikosR** [comment]
Imagine me, having to keep them up to date all this time...

**Pull request closed without merging**
